### ISSUE TITLE
sse: api.swap is not a function

### ISSUE THREAD

**Issue by mailq** [bigskysoftware/htmx-extensions#125]
First of all I'm not a JavaScript developer, so I do not know how to debug this stuff.

Using the SSE extension (current master or via unpkg.com@2.2.2) does not swap any content. Instead it throws an exception on the browser's console:

```
Uncaught TypeError: api.swap is not a function
    at swap (sse.js:283:9)
    at EventSource.listener (sse.js:122:11)
swap @ sse.js:283
listener @ sse.js:122
```

And sure enough, in the latest htmx.min.js or htmx.js there is no appropriate function called swap(). Or at least the one which wants to be called should have three parameters, whereas the one in htmx.js has five parameters. It has five parameters in the v1 branch, too.

The SSE extension does connect to the server, it receives the (correct) message, but then fails to swap.

So what did I miss?

If it matters, this is the HTML snippet:
```
<div hx-ext="sse" sse-connect="/app/message/watch" sse-swap="message" hx-target="#mailbox" hx-swap="beforeend">
  auto refresh: on
</div>
```

**Comment by mailq** [comment]
Never mind. It was a browser cache issue.
